version: "3"
services:
  scoreboard:
    build:
      context: .
      args:
        NODE_ENV: production
    restart: always
    ports:
      - 3000:3000
    volumes:
      - session:/workspace/sessions
      - grade:/workspace/data

volumes:
  session:
    driver: local
  grade:
    driver: local
